### ISSUE TITLE
Only one CA certificate is supported in mtls ca file

### ISSUE THREAD

**Issue by marcolan018** [observatorium/api#136]
Currently when loading certificate from mtls ca file, only the first certificate will be loaded to verify the incoming client certificates. If there are more than one certificates located in the ca file, others will be ignored.(https://github.com/observatorium/api/blob/cbff1da9ba9371516a6254db359ae33545aefdf7/main.go#L239-L251)

It's a very common scenario  that more than one certificates are required. e.g. assume thousands of clients are talking to api gateway now. The CA certificates renewed, there will be a period that some clients will use the certificates signed by new CA cert, but some still using the certificates signed by old CA cert.

**Comment by squat** [comment]
This sounds totally reasonable to me and should be quite straightforward to implement 👍
