### ISSUE TITLE
Make gRPC interceptors to Support Authz/Authn

### ISSUE THREAD

**Issue by squat** [observatorium/api#158]
We can't implement the custom authz logic for Observatorum in OpenTelemetry, so we will need to proxy the authorized gRPC requests. Unfortunately, in order to provide authz, we also need authn. This means we will need to build a gRPC auth interceptor proxy into Observatorium. The proxies must be application agnostic, that is, they shouldn't know anything about the application-level proto for the endpoints to which they are forwarding. They should only look at frame headers for auth information.

**Comment by esnible** [comment]
Can we close this because we now have https://github.com/observatorium/api/blob/main/authorization/grpc.go ?

**Comment by matej-g** [comment]
Yes, looks like this has been satisfied, closing, thanks @esnible :+1:
