### ISSUE TITLE
"make test-interactive" gives "exec format error" on MacOS

### ISSUE THREAD

**Issue by esnible** [observatorium/api#189]
"make test-interactive" gives "exec format error" on MacOS.

Almost certainly the problem is that the _Makefile_ builds _observatorium_api_ for the OS, but then packages the OS-specific binary in the Linux-specific container image.

Work around:

```bash
rm ./observatorium-api
OS=linux GOARCH=amd64 make test-interactive
```

Output without the work-around
```
16:13:17 Starting observatorium_api
16:13:18 observatorium_api: standard_init_linux.go:228: exec user process caused: exec format error
16:13:52 
Error: No such object: e2e_interactive-observatorium_api

    interactive_test.go:33: interactive_test.go:33:
        
         unexpected error: docker container observatorium_api failed to start: exit status 1
```

**Comment by matej-g** [comment]
Thanks for the report @esnible! https://github.com/observatorium/api/pull/190 should fix this.
