### ISSUE TITLE
Rules API: Response code is internal server error even if caused by bad request

### ISSUE THREAD

**Issue by matej-g** [observatorium/api#234]
We are currently always returning `500` if [(un)marhsalling](https://github.com/observatorium/api/blob/28835ce867353095ddf559db4762ee3b4eddde45/api/metrics/v1/rules.go#L132) of the rules provided in the YAML by the user fails. However, more often than not, the unmarshalling will fail due to user error, because for example the provided YAML is not valid. We should be able to detect these cases, and if that happens, return `400` instead.  (This can also lead to false positives when it comes to monitoring, since it could artificially increase number of `500` server responses, even though these are user errors)

**Comment by jessicalins** [comment]
solved by https://github.com/observatorium/api/pull/235 - closing
