### ISSUE TITLE
Trace Read tenancy architecture and implementation

### ISSUE THREAD

**Issue by esnible** [observatorium/api#268]
Now that https://github.com/observatorium/api/pull/252 has merged we can query traces through Observatorium.

Unfortunately, we don't have a full story for queries because Jaeger doesn't support tenancy yet.  (For writing traces we handle tenancy at the OTel collector level, see https://github.com/observatorium/observatorium/pull/461 ).

In order to make https://github.com/observatorium/api/issues/267 meaningful we need to decide how to handle tenancy for queries.  I see three approaches.  I would like to start discussion for the correct approach.

- Do nothing, and wait for the Jaeger community to implement https://github.com/jaegertracing/jaeger/issues/3427
- Allow templates beyond simple hostnames in `-trace.read.endpoint`.  Using this approach we could say `-trace.read.endpoint="jaeger-{tenant}:14250", and Observatorium would send traces appropriately to multiple Jaeger instances.
- Create an additional reverse proxy which forwards the same way, perhaps by generating an Envoy or Nginx config from JSONNET that would take the role for queries that OTel takes for posting traces.

@pavolloffay has suggested the template endpoint approach would be best.  (When Jaeger gets multi-tenancy we would simply stop supplying templates to `-trace.read.endpoint`.)

I'd like to get this in before https://github.com/observatorium/api/issues/267 so that I can test properly.

**Comment by matej-g** [comment]
Given the current situation without native multi-tenancy features and considering the fact that we'll need to have a Jaeger instance per tenant either way, the second option also seems like the simplest way to go for me.
