### ISSUE TITLE
HTTP handler monitoring middleware isn't the topmost in the middleware stack

### ISSUE THREAD

**Issue by douglascamata** [observatorium/api#300]
While working on #295, I noticed that the HTTP metrics middleware isn't mounted at the top of the stack. This may cause some HTTP requests to not be properly instrumented when a given middleware writes the response and stop the chain execution.

For instance, [here we mount the authentication middlewares for each tenant](https://github.com/observatorium/api/blob/fb1e8ad0e52c7738aa124597dcb9f74955e821c0/main.go#L529). In case the tenant is using OIDC authentication, the OIDC middleware can make the request finish early for a number of reasons without calling the next middlewares, [like if the `Authorization` header is invalid](https://github.com/observatorium/api/blob/b3a191802b501fb6051e73f2f986240e1e406be4/authentication/oidc.go#L283). When this happens, [the rest of the middleware stack](https://github.com/observatorium/api/blob/fb1e8ad0e52c7738aa124597dcb9f74955e821c0/main.go#L561) never gets executed.

## Proposed solution

Mount the HTTP handler monitoring middleware at the top of the stack to ensure that all the HTTP requests get instrumented.

**Comment by PhilipGough** [comment]
@douglascamata can we close this now based on #430?

**Comment by PhilipGough** [comment]
Does #430 close this or is there still some more to do?

**Comment by douglascamata** [comment]
@PhilipGough I think it does solve everything, so I'll close it as solved. If there's anything else to be fixed we can open new issues. Thanks! 🙇
