### ISSUE TITLE
Consider adopting the Prometheus JSON format for error responses

### ISSUE THREAD

**Issue by matej-g** [observatorium/api#319]
Referring to: https://prometheus.io/docs/prometheus/latest/querying/api/#format-overview

We chatted about this with @saswatamcode (off the back of https://github.com/observatorium/api/pull/318) and we are finding the current approach with mixed JSON (which is returned in case of `2xx` responses) and plain-text (returned for `4xx` and `5xx`) responses not satisfactory.

Ideally, we should enhance the API spec to specify that the error responses should be also JSON and adapt the API to return the Prometheus JSON format for errors. This would have added benefit of using the well-known Prometheus format, which would make user experience nicer, especially in the downstream web UI. For example, right now Thanos UI will fail to show an error response, since it expects JSON and cannot parse a plain-text response.

**Comment by squat** [comment]
Nice, we recently did the same in prom label proxy: https://github.com/prometheus-community/prom-label-proxy/pull/108

**Comment by saswatamcode** [comment]
Closing as this has been implemented! 🙂
