### ISSUE TITLE
OIDC authenticator skips identity check if no username or group claim are present

### ISSUE THREAD

**Issue by douglascamata** [observatorium/api#331]
The `oidcAuthenticator.checkAuth` function has logic that can facilitate the introduction of security issues.

It properly verifies the OIDC token (checks issuer and signature), but if there's no username or group claim configured for a tenant it will happily do no identity check and consider the token authorized. 

So it enables something like this to happen:

1. Tenant A and B use the same OIDC server to authenticate (will pass issuer and signature check).
2. Tenant B has bad configuration in Observatorium, without username or group claims.
3. Tenant A can send data to Tenant B (no identity check will happen).

The current logic is as follows:

```go
func (a oidcAuthenticator) checkAuth(ctx context.Context, token string) (context.Context, string, int, codes.Code) {
    # Check the issuer and signature.
    idToken, err := a.verifier.Verify(oidc.ClientContext(ctx, a.client), token)
    ...
    # If there is a configured username claim for this tenant's authenticator, check it.
    if a.config.usernameClaim != "" {
        ...
    }
    ...
    # If there is a group claim for this tenant's authenticator, check it.
    if a.config.GroupClaim != "" {
        ...
    }
    # Bad logic here: no username or group claim for this tenant? Authorized without identity check!
    return ctx, "", http.StatusOK, codes.OK
}
```

I don't think it poses a security risk at the moment, but I do believe we should take preventive action and enforce that all tenants configure either username or group claims to avoid problems.

By default, we should consider everything unauthorized.

**Comment by periklis** [comment]
@douglascamata Isn't this behavior intended in using the API together with the token-refresher?

**Comment by douglascamata** [comment]
My point is, I don't think we ensure that the token's subject has access to the tenant.

**Comment by douglascamata** [comment]
Nevermind, I understand now how it's working under the hood. 🤔 

I am closing this to avoid confusion.
